### ISSUE TITLE
Electron window doesn't show up after running

### ISSUE THREAD

**Issue by achraflamhamdi** [codingwithjustin/react-electron#4]
I'm new in working with React and Electron together in one project, I followed this [youtube video](https://www.youtube.com/watch?v=oAaS9ix8pes) but when running, the electron window doesn't pop up while React server is all set fine, I don't know where is the problem while I'm convinced that I followed all the steps correctly. Please Help !!!

**Comment by panfeelove** [comment]
@achraflamhamdi how did you resolved it?
